# Generated by Django 4.1.6 on 2023-02-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameUser",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_joined_game", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=20)),
                ("wins", models.IntegerField(default=0)),
                ("kills", models.IntegerField(default=0)),
                ("topfrags", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.gameuser"
                    ),
                ),
            ],
        ),
    ]
