# Generated by Django 4.1.6 on 2023-02-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameuser",
            options={"verbose_name": "Game User"},
        ),
        migrations.AlterModelOptions(
            name="userstats",
            options={"verbose_name": "User Stats"},
        ),
    ]
