# Generated by Django 4.1.6 on 2023-02-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_gameuser_options_alter_userstats_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameuser",
            options={"verbose_name": "Game User", "verbose_name_plural": "Game Users"},
        ),
        migrations.AlterModelOptions(
            name="userstats",
            options={"verbose_name": "User Stat", "verbose_name_plural": "User Stats"},
        ),
    ]
