# Generated by Django 4.1.6 on 2023-02-08 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_gameuser_options_alter_userstats_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWeaponStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weapon", models.CharField(max_length=20)),
                ("kills", models.IntegerField(default=0)),
                (
                    "stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.userstats"
                    ),
                ),
            ],
            options={
                "verbose_name": "User Weapon Stat",
            },
        ),
    ]
