# Generated by Django 4.1.6 on 2023-02-08 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_userweaponstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userweaponstats",
            name="stats",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.gameuser"
            ),
        ),
    ]
