# Generated by Django 4.1.6 on 2023-02-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_userweaponstats_stats"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userweaponstats",
            old_name="stats",
            new_name="user",
        ),
    ]
