# Generated by Django 4.1.6 on 2023-02-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_stats_userweaponstats_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
