# Generated by Django 4.1.6 on 2023-02-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gameuser_xp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstats',
            options={'verbose_name': 'UserStat'},
        ),
        migrations.AddField(
            model_name='gameuser',
            name='events_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='events_hosted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='heals_given',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserMedals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal_name', models.CharField(max_length=50)),
                ('tier', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gameuser')),
            ],
            options={
                'verbose_name': 'User Medal',
            },
        ),
    ]
